name: Deploy Terraform Environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

concurrency:
  group: terraform-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: envs/${{ inputs.environment }}

    strategy:
      matrix:
        action: [init, plan, apply]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}  

      - name: Setup Terraform and Terragrunt
        uses: ./.github/actions/setup-terraform
        
      - name: Terragrunt Init
        run: terragrunt init

      - name: Terragrunt ${{ matrix.action }}
        run: |
          echo "Running terragrunt ${{ matrix.action }}"
          if [[ "${{ matrix.action }}" == "plan" ]]; then
            terragrunt plan -out=plan.tfplan
          elif [[ "${{ matrix.action }}" == "apply" ]]; then
            terragrunt apply -auto-approve plan.tfplan || terragrunt apply -auto-approve
          else
            terragrunt ${{ matrix.action }}
          fi